const fs = require('fs')
const path = require('path')
const LRU = require('lru-cache')
const express = require('express')
const favicon = require('serve-favicon')
const compression = require('compression')
const resolve = file => path.resolve(__dirname, file)
const { createBundleRenderer } = require('vue-server-renderer')

const isProd = process.env.NODE_ENV === 'production'
const useMicroCache = process.env.MICRO_CACHE !== 'false'
const serverInfo =
  `express/${require('express/package.json').version} ` +
  `vue-server-renderer/${require('vue-server-renderer/package.json').version}`

const app = express()
// 引入 socket.io
const http = require('http').Server(app)
const io = require('socket.io')(http)

const template = fs.readFileSync(resolve('./src/index.template.html'), 'utf-8')

function createRenderer (bundle, options) {
  // https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/README.md#why-use-bundlerenderer
  return createBundleRenderer(bundle, Object.assign(options, {
    template,
    // for component caching
    cache: LRU({
      max: 1000,
      maxAge: 1000 * 60 * 15
    }),
    // this is only needed when vue-server-renderer is npm-linked
    basedir: resolve('./dist'),
    // recommended for performance
    runInNewContext: false
  }))
}

let renderer
let readyPromise
if (isProd) {
  // In production: create server renderer using built server bundle.
  // The server bundle is generated by vue-ssr-webpack-plugin.
  const bundle = require('./dist/vue-ssr-server-bundle.json')
  // The client manifests are optional, but it allows the renderer
  // to automatically infer preload/prefetch links and directly add <script>
  // tags for any async chunks used during render, avoiding waterfall requests.
  const clientManifest = require('./dist/vue-ssr-client-manifest.json')
  renderer = createRenderer(bundle, {
    clientManifest
  })
} else {
  // In development: setup the dev server with watch and hot-reload,
  // and create a new renderer on bundle / index template update.
  readyPromise = require('./build/setup-dev-server')(app, (bundle, options) => {
    renderer = createRenderer(bundle, options)
  })
}

const serve = (path, cache) => express.static(resolve(path), {
  maxAge: cache && isProd ? 1000 * 60 * 60 * 24 * 30 : 0
})

app.use(compression({ threshold: 0 }))
app.use(favicon('./public/logo.png'))
app.use('/dist', serve('./dist', true))
app.use('/public', serve('./public', true))
app.use('/manifest.json', serve('./manifest.json', true))
// app.use('/service-worker.js', serve('./dist/service-worker.js'))

// 1-second microcache.
// https://www.nginx.com/blog/benefits-of-microcaching-nginx/
const microCache = LRU({
  max: 100,
  maxAge: 1000
})

// since this app has no user-specific content, every page is micro-cacheable.
// if your app involves user-specific content, you need to implement custom
// logic to determine whether a request is cacheable based on its url and
// headers.
const isCacheable = req => useMicroCache

function render (req, res) {
  const s = Date.now()

  res.setHeader('Content-Type', 'text/html')
  res.setHeader('Server', serverInfo)

  const handleError = err => {
    if (err && err.code === 404) {
      res.status(404).end('404 | Page Not Found')
    } else {
      // Render Error Page or Redirect
      res.status(500).end('500 | Internal Server Error')
      console.error(`error during render : ${req.url}`)
      console.error(err.stack)
    }
  }

  const cacheable = isCacheable(req)
  if (cacheable) {
    const hit = microCache.get(req.url)
    if (hit) {
      if (!isProd) {
        console.log(`cache hit!`)
      }
      return res.end(hit)
    }
  }

  const context = {
    title: '星云聊天室', // default title
    url: req.url
  }
  renderer.renderToString(context, (err, html) => {
    if (err) {
      return handleError(err)
    }
    res.end(html)
    if (cacheable) {
      microCache.set(req.url, html)
    }
    if (!isProd) {
      console.log(`whole request: ${Date.now() - s}ms`)
    }
  })
}

app.get('*', isProd ? render : (req, res) => {
  readyPromise.then(() => render(req, res))
})

const md5 = require('md5')

// 在线用户
var onlineUsers = {}
// 当前在线人数
var onlineCount = 0
// 所有在线聊天记录
var messages = []

io.on('connection', function (socket) {
  // console.log('a user connected')
  // console.log(io.sockets.sockets)
  // 监听新用户加入
  socket.on('login', function (obj) {
    // 将新加入用户的唯一标识当作socket的名称，后面退出的时候会用到
    socket.name = obj.userid
    // 检查在线列表，如果不在里面就加入
    if (!onlineUsers.hasOwnProperty(obj.userid)) {
      onlineUsers[obj.userid] = obj.username
      // 在线人数+1
      onlineCount++
    }
    // 向所有客户端广播用户加入
    io.emit('login', {onlineUsers: onlineUsers, onlineCount: onlineCount, user: obj})
    console.log(obj.username + '加入了聊天室 当前现在人数为:' + onlineCount)
  })
  // 监听用户退出
  socket.on('disconnect', function () {
    // 将退出的用户从在线列表中删除
    if (onlineUsers.hasOwnProperty(socket.name)) {
      // 退出用户的信息
      let obj = {userid: socket.name, username: onlineUsers[socket.name]}
      // 删除
      delete onlineUsers[socket.name]
      // 在线人数-1
      onlineCount--
      // 向所有客户端广播用户退出
      io.emit('logout', {onlineUsers: onlineUsers, onlineCount: onlineCount, user: obj})
      console.log(`${obj.username} 退出了聊天室 目前同时在线人数: ${onlineCount}`)
    }
  })
  // 监听用户发布聊天内容
  socket.on('message', function (obj) {
    // 给每条消息加一个ID为了识别离线消息
    obj.id = md5(obj.userid + obj.content + new Date())
    // 向所有客户端广播发布的消息
    io.emit('message', obj)
    messages.push(obj)
    console.log(obj.username + '说：' + obj.content)
  })

  // 监听用户离线的聊天内容
  socket.on('outlineMessage', function (obj) {
    let index = messages.findIndex(item => item.id === obj.id)
    if (index < messages.length - 1) {
      let list = messages.slice(index + 1, messages.length)
      // 向所有客户端广播发布的消息
      io.sockets.sockets[obj.socketId].emit('outlineMessage', list)
    }
  })
})

const port = process.env.PORT || 8080
app.listen(port, () => {
  console.log(`server started at localhost:${port}`)
})

http.listen(3000, function () {
  console.log('listening on *:3000')
})
